openapi: 3.0.3
info:
  title: forum
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /forum-api/games:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
              examples: {}
        '500':
          $ref: '#/components/responses/SystemError'
      operationId: get-games
      description: 全てのゲームのIDとなまえを返す
  '/forum-api/games/{game}/posts':
    parameters:
      - schema:
          type: string
        name: game
        in: path
        required: true
        description: game id
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-games-posts
      description: そのゲームに投稿されたすべてのポストを取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          $ref: '#/components/responses/SystemError'
    post:
      summary: ''
      operationId: post-games-post
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/SystemError'
        '409':
          $ref: '#/components/responses/SystemError'
        '500':
          $ref: '#/components/responses/SystemError'
      description: そのゲームに書き込みを投稿する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
        description: 掲示板書き込みデータ
  '/forum-api/posts/{uuid}':
    parameters:
      - schema:
          type: string
        name: uuid
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-posts-uuid
      responses:
        '200':
          description: OK
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteRequest'
components:
  schemas:
    Game:
      title: Game
      type: object
      description: 取り扱うゲームのモデル
      x-examples:
        example:
          value:
            id: pso2ngs
            name: PSO2 NGS
      properties:
        id_name:
          type: string
          description: ゲームの識別子.URLに使用される
        view_name:
          type: string
          description: ゲームの名前。HTML上に表示するもの
      required:
        - id_name
        - view_name
    Post:
      title: Post
      type: object
      description: ユーザ投稿モデル
      x-examples:
        example:
          value:
            id: 1
            gameId: pso2ngs
            playerName: ブロントさん
            purpose: PLAY
            vcUse: true
            device: PC、PS5
            comment: あれこれそれ
            createdAt: '2019-08-24T14:15:22Z'
      properties:
        uuid:
          type: string
          description: シーケンシャルID
        writeDay:
          type: string
          format: date
        gameId:
          type: string
          description: 投稿先のゲームのID
        title:
          type: string
        server:
          type: string
        playerName:
          type: string
          description: プレイヤーの名前
          minLength: 1
          maxLength: 20
        purpose:
          type: string
          enum:
            - PLAY
            - FRIEND
            - GURUGURU
            - END_CONTENT
            - HELPME
            - TEAM_LANCH
            - TEAM_SCOUT
            - TEAM_JOIN
            - EVENT
            - TRADE
            - OTHER
          example: PLAY
        vcUse:
          type: string
          enum:
            - USE
            - UNUSE
            - EITHER
        device:
          type: string
          minLength: 0
          maxLength: 30
        comment:
          type: string
          minLength: 1
          maxLength: 400
        createdAt:
          type: string
          format: date-time
        userData:
          $ref: '#/components/schemas/UserData'
        deleteKey:
          type: string
        tags:
          type: array
          description: 相手に求めることを記載するタグ
          items:
            $ref: '#/components/schemas/Tags'
        selfTags:
          type: array
          description: 自分に当てはまることを記載するタグ
          items:
            $ref: '#/components/schemas/Tags'
        playTime:
          type: array
          items:
            type: string
            enum:
              - WEEKDAYS_M
              - WEEKDAYS_L
              - WEEKDAYS_N
              - WEEKDAYS_MN
              - WEEKDAYS_EM
              - HOLIDAYS_EM
              - HOLIDAYS_M
              - HOLIDAYS_L
              - HOLIDAYS_N
              - HOLIDAYS_MN
              - BEST_EFFORT
              - RANDOM
              - WEEKDAYS
              - HOLIDAYS
      required:
        - gameId
        - title
        - playerName
        - purpose
        - vcUse
        - device
        - comment
    Error:
      title: Error
      type: object
      description: 汎用エラーモデル
      properties:
        code:
          type: string
          description: エラーのハンドリングを示すパラメータ
          enum:
            - INTERNAL
            - CONFLICT
            - MAINTENANCE
          example: INTERNAL
        message:
          type: string
          description: エラーに関する説明
      required:
        - code
        - message
    UserData:
      title: UserData
      type: object
      properties:
        ipAddr:
          type: string
        userAgent:
          type: string
    Tags:
      title: Tags
      type: object
      properties:
        id:
          type: string
          enum:
            - PS_EX
            - PS_JOY
            - PS_EASY
            - TIME_SOCIETY
            - TIME_STUDENT
            - YEARS_10
            - YEARS_20
            - YEARS_OV_30
            - PLAY_EASY
            - PLAY_VETERAN
            - PLAY_HERO
            - JOB_ACK
            - JOB_DEF
            - JOB_HEAL
      required:
        - id
    DeleteRequest:
      title: DeleteRequest
      type: object
      properties:
        deleteKey:
          type: string
        gameId:
          type: string
        writeDay:
          type: string
      required:
        - deleteKey
        - gameId
        - writeDay
  responses:
    SystemError:
      description: エラーレスポンス
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
